name: Auto Absen UNBIN

on:
  schedule:
    - cron: '*/5 2-3 * * *'   # Setiap 5 menit antara 09:00-10:00 WIB
    - cron: '*/5 5-6 * * *'   # Setiap 5 menit antara 12:00-13:00 WIB
    - cron: '*/5 6-7 * * *'   # Setiap 5 menit antara 13:00-14:00 WIB
  workflow_dispatch:
  push:

jobs:
  test-absen:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pytz
        
    - name: Run test absen
      run: python absen.py --test
      
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-absensi-logs
        path: |
          absen/log/
          absen/log/screenshots/
        retention-days: 7
        
  scheduled-absen:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pytz
        
    - name: Run absen script
      run: python absen.py
      
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: absensi-logs
        path: |
          absen/log/
          absen/log/screenshots/
        retention-days: 7