name: Auto Absen UNBIN

on:
  schedule:
    # Jadwal 1: 09:30 WIB (02:30 UTC)
    - cron: '25,26,27,28,29,30,31,32,33,34,35 2 * * *'  # 09:25-09:35 WIB
    
    # Jadwal 2: 12:30 WIB (05:30 UTC)
    - cron: '25,26,27,28,29,30,31,32,33,34,35 5 * * *'  # 12:25-12:35 WIB
    
    # Jadwal 3: 13:30 WIB (06:30 UTC)
    - cron: '25,26,27,28,29,30,31,32,33,34,35 6 * * *'  # 13:25-13:35 WIB
  workflow_dispatch:
  push:

jobs:
  test-absen:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pytz
        
    - name: Run test absen
      env: 
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      run: python absen.py --test
      
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-absensi-logs
        path: |
          absen/log/
          absen/log/screenshots/
        retention-days: 7
        
  scheduled-absen:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pytz
        
    - name: Run absen script
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      run: python absen.py
      
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: absensi-logs
        path: |
          absen/log/
          absen/log/screenshots/
        retention-days: 7