name: Auto Absen UNBIN

on:
  schedule:
    - cron: '28,29,30,31,32 2 * * *'  # 09:28-09:32 WIB (02:28-02:32 UTC)
    - cron: '28,29,30,31,32 6 * * *'  # 13:28-13:32 WIB (06:28-06:32 UTC)
  workflow_dispatch:
  push:

jobs:
  test-absen:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pytz
        
    - name: Run test absen
      env:
        UNBIN_USERNAME: ${{ secrets.UNBIN_USERNAME }}
        UNBIN_PASSWORD: ${{ secrets.UNBIN_PASSWORD }}
      run: python absen.py --test
      
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-absensi-logs
        path: |
          absen/log/
          absen/log/screenshots/
        retention-days: 90
        
  scheduled-absen:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pytz
        
    - name: Run absen script
      env:
        UNBIN_USERNAME: ${{ secrets.UNBIN_USERNAME }}
        UNBIN_PASSWORD: ${{ secrets.UNBIN_PASSWORD }}
      run: python absen.py
      
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: absensi-logs
        path: |
          absen/log/
          absen/log/screenshots/
        retention-days: 90